# Generated by Django 6.0 on 2026-01-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='devtool',
        ),
        migrations.AddField(
            model_name='idea',
            name='devtools',
            field=models.ManyToManyField(related_name='ideas', to='tool.devtool'),
        ),
    ]
